SEED_DATA = {
    "ProviderOrganization": [
        {
            "org_type": "clinic",
            "name": "Harbor Inclusive Health Center",
            "description": "Community-based clinic offering gender-affirming primary care, hormone therapy support, mental health referrals, and care navigation for LGBTQ+ patients.",
            "website_url": "https://example.org/harbor-inclusive-health",
            "booking_url": "https://example.org/harbor-inclusive-health/book",
            "phone": "+1-212-555-0142",
            "email": "care@harborinclusive.example",
            "is_active": True,
            "last_verified_at": "2026-03-12T10:00:00Z",
        },
        {
            "org_type": "hospital_program",
            "name": "Lakeside Gender Health Program",
            "description": "Hospital-based gender health program providing coordinated care across primary care, hormone therapy, surgery referrals, behavioral health, and social work.",
            "website_url": "https://example.org/lakeside-gender-health",
            "booking_url": "https://example.org/lakeside-gender-health/appointments",
            "phone": "+1-312-555-0188",
            "email": "gendercare@lakeside.example",
            "is_active": True,
            "last_verified_at": "2026-03-10T09:30:00Z",
        },
        {
            "org_type": "telehealth",
            "name": "OpenPath Telehealth Care",
            "description": "Virtual-first provider offering gender-affirming consultations, hormone therapy follow-up, lab coordination, and care navigation in selected states.",
            "website_url": "https://example.org/openpath-telehealth",
            "booking_url": "https://example.org/openpath-telehealth/start",
            "phone": "+1-888-555-0199",
            "email": "support@openpathcare.example",
            "is_active": True,
            "last_verified_at": "2026-03-14T11:00:00Z",
        },
        {
            "org_type": "private_practice",
            "name": "Evergreen Affirming Therapy",
            "description": "Private behavioral health practice focused on LGBTQ+ affirming therapy, gender exploration support, documentation letters, and referral guidance.",
            "website_url": "https://example.org/evergreen-therapy",
            "booking_url": "https://example.org/evergreen-therapy/intake",
            "phone": "+1-503-555-0133",
            "email": "hello@evergreentherapy.example",
            "is_active": True,
            "last_verified_at": "2026-03-05T15:20:00Z",
        },
        {
            "org_type": "nonprofit",
            "name": "BridgePoint LGBTQ Resource Clinic",
            "description": "Nonprofit clinic offering care navigation, community referrals, HIV/STI testing, insurance enrollment support, and affirming provider referrals.",
            "website_url": "https://example.org/bridgepoint-lgbtq",
            "booking_url": "https://example.org/bridgepoint-lgbtq/services",
            "phone": "+1-404-555-0164",
            "email": "info@bridgepointlgbtq.example",
            "is_active": True,
            "last_verified_at": "2026-03-08T13:45:00Z",
        },
        {
            "org_type": "clinic",
            "name": "North Star Community Health",
            "description": "Primary care clinic with gender-affirming hormone therapy, preventive care, lab monitoring, and insurance navigation.",
            "website_url": "https://example.org/north-star-community",
            "booking_url": "https://example.org/north-star-community/request-visit",
            "phone": "+1-617-555-0121",
            "email": "appointments@northstarhealth.example",
            "is_active": True,
            "last_verified_at": "2026-02-28T12:00:00Z",
        },
        {
            "org_type": "hospital_program",
            "name": "Cedar Valley Trans Health Program",
            "description": "Multidisciplinary hospital program supporting hormone therapy, surgical consultation, reproductive health, voice care, and behavioral health referrals.",
            "website_url": "https://example.org/cedar-valley-trans-health",
            "booking_url": "https://example.org/cedar-valley-trans-health/referrals",
            "phone": "+1-206-555-0175",
            "email": "transhealth@cedarvalley.example",
            "is_active": True,
            "last_verified_at": "2026-03-11T16:10:00Z",
        },
        {
            "org_type": "private_practice",
            "name": "Spectrum Family Medicine",
            "description": "Private family medicine practice providing adult primary care, hormone therapy management, preventive screening, and affirming intake workflows.",
            "website_url": "https://example.org/spectrum-family-medicine",
            "booking_url": "https://example.org/spectrum-family-medicine/book",
            "phone": "+1-720-555-0158",
            "email": "frontdesk@spectrumfamily.example",
            "is_active": True,
            "last_verified_at": "2026-03-09T10:40:00Z",
        },
        {
            "org_type": "clinic",
            "name": "Rainbow Bridge Wellness Clinic",
            "description": "Wellness clinic offering primary care, sexual health services, PrEP, hormone therapy follow-up, and referrals to affirming specialists.",
            "website_url": "https://example.org/rainbow-bridge-wellness",
            "booking_url": "https://example.org/rainbow-bridge-wellness/schedule",
            "phone": "+1-305-555-0117",
            "email": "careteam@rainbowbridge.example",
            "is_active": True,
            "last_verified_at": "2026-03-13T14:15:00Z",
        },
        {
            "org_type": "telehealth",
            "name": "TrueNorth Virtual Gender Care",
            "description": "Telehealth-focused gender care service supporting hormone therapy consultations, follow-up visits, lab coordination, and pharmacy guidance.",
            "website_url": "https://example.org/truenorth-virtual-care",
            "booking_url": "https://example.org/truenorth-virtual-care/get-started",
            "phone": "+1-855-555-0181",
            "email": "support@truenorthgender.example",
            "is_active": True,
            "last_verified_at": "2026-03-15T09:00:00Z",
        },
        {
            "org_type": "nonprofit",
            "name": "Community Pride Health Access",
            "description": "Nonprofit resource center helping LGBTQ+ patients find affirming care, understand insurance options, and connect with local support services.",
            "website_url": "https://example.org/community-pride-access",
            "booking_url": "https://example.org/community-pride-access/contact",
            "phone": "+1-713-555-0126",
            "email": "navigation@communitypride.example",
            "is_active": True,
            "last_verified_at": "2026-03-06T17:30:00Z",
        },
        {
            "org_type": "clinic",
            "name": "UnityCare Gender Wellness",
            "description": "Outpatient clinic providing gender-affirming primary care, hormone therapy, lab monitoring, mental health referrals, and preventive care.",
            "website_url": "https://example.org/unitycare-gender-wellness",
            "booking_url": "https://example.org/unitycare-gender-wellness/appointments",
            "phone": "+1-415-555-0104",
            "email": "appointments@unitycare.example",
            "is_active": True,
            "last_verified_at": "2026-03-07T11:25:00Z",
        },
    ],
    "ProviderLocation": [
        {
            "organization": "Harbor Inclusive Health Center",
            "address_line1": "214 West 29th Street",
            "address_line2": "Suite 402",
            "city": "New York",
            "state_code": "NY",
            "zip_code": "10001",
            "latitude": "40.748817",
            "longitude": "-73.985428",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": True,
            "public_transit_notes": True,
        },
        {
            "organization": "Lakeside Gender Health Program",
            "address_line1": "811 North Clark Street",
            "address_line2": "Floor 3",
            "city": "Chicago",
            "state_code": "IL",
            "zip_code": "60610",
            "latitude": "41.898370",
            "longitude": "-87.631520",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": True,
            "public_transit_notes": True,
        },
        {
            "organization": "OpenPath Telehealth Care",
            "address_line1": "Virtual Care Office",
            "address_line2": "",
            "city": "Austin",
            "state_code": "TX",
            "zip_code": "73301",
            "latitude": "30.267153",
            "longitude": "-97.743057",
            "is_primary": True,
            "wheelchair_accessible": False,
            "gender_neutral_restrooms": False,
            "public_transit_notes": False,
        },
        {
            "organization": "Evergreen Affirming Therapy",
            "address_line1": "1420 Northwest Everett Street",
            "address_line2": "Suite 210",
            "city": "Portland",
            "state_code": "OR",
            "zip_code": "97209",
            "latitude": "45.525135",
            "longitude": "-122.685837",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": True,
            "public_transit_notes": True,
        },
        {
            "organization": "BridgePoint LGBTQ Resource Clinic",
            "address_line1": "75 Peachtree Place NE",
            "address_line2": "",
            "city": "Atlanta",
            "state_code": "GA",
            "zip_code": "30309",
            "latitude": "33.780380",
            "longitude": "-84.386330",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": True,
            "public_transit_notes": True,
        },
        {
            "organization": "North Star Community Health",
            "address_line1": "420 Cambridge Street",
            "address_line2": "Suite 110",
            "city": "Boston",
            "state_code": "MA",
            "zip_code": "02134",
            "latitude": "42.359314",
            "longitude": "-71.127205",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": True,
            "public_transit_notes": True,
        },
        {
            "organization": "Cedar Valley Trans Health Program",
            "address_line1": "905 East Madison Street",
            "address_line2": "Medical Arts Building",
            "city": "Seattle",
            "state_code": "WA",
            "zip_code": "98122",
            "latitude": "47.609722",
            "longitude": "-122.324722",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": True,
            "public_transit_notes": True,
        },
        {
            "organization": "Spectrum Family Medicine",
            "address_line1": "1550 Wynkoop Street",
            "address_line2": "Suite 330",
            "city": "Denver",
            "state_code": "CO",
            "zip_code": "80202",
            "latitude": "39.752998",
            "longitude": "-104.999001",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": False,
            "public_transit_notes": True,
        },
        {
            "organization": "Rainbow Bridge Wellness Clinic",
            "address_line1": "310 Biscayne Boulevard",
            "address_line2": "Suite 204",
            "city": "Miami",
            "state_code": "FL",
            "zip_code": "33132",
            "latitude": "25.776800",
            "longitude": "-80.186500",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": True,
            "public_transit_notes": True,
        },
        {
            "organization": "TrueNorth Virtual Gender Care",
            "address_line1": "Virtual Care Office",
            "address_line2": "",
            "city": "Minneapolis",
            "state_code": "MN",
            "zip_code": "55401",
            "latitude": "44.977753",
            "longitude": "-93.265011",
            "is_primary": True,
            "wheelchair_accessible": False,
            "gender_neutral_restrooms": False,
            "public_transit_notes": False,
        },
        {
            "organization": "Community Pride Health Access",
            "address_line1": "622 Westheimer Road",
            "address_line2": "",
            "city": "Houston",
            "state_code": "TX",
            "zip_code": "77006",
            "latitude": "29.744610",
            "longitude": "-95.389320",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": True,
            "public_transit_notes": True,
        },
        {
            "organization": "UnityCare Gender Wellness",
            "address_line1": "1725 Market Street",
            "address_line2": "Suite 250",
            "city": "San Francisco",
            "state_code": "CA",
            "zip_code": "94103",
            "latitude": "37.771720",
            "longitude": "-122.421210",
            "is_primary": True,
            "wheelchair_accessible": True,
            "gender_neutral_restrooms": True,
            "public_transit_notes": True,
        },
    ],
    "Service": [
        {"name": "Primary Care"},
        {"name": "Hormone Therapy"},
        {"name": "HRT Follow-Up Care"},
        {"name": "Lab Monitoring"},
        {"name": "Mental Health Counseling"},
        {"name": "Psychiatry"},
        {"name": "Surgery Consultation"},
        {"name": "Surgery Referral Support"},
        {"name": "Voice Therapy"},
        {"name": "Fertility Preservation"},
        {"name": "Sexual and Reproductive Health"},
        {"name": "PrEP and HIV Prevention"},
        {"name": "Care Navigation"},
        {"name": "Insurance Navigation"},
        {"name": "Pharmacy Coordination"},
        {"name": "Youth Gender Care"},
    ],
    "OrganizationService": [
        {
            "organization": "Harbor Inclusive Health Center",
            "service": "Primary Care",
            "delivery_mode": "both",
            "age_group": "adult",
            "note": "Adult primary care with affirming intake and referrals for specialized services.",
        },
        {
            "organization": "Harbor Inclusive Health Center",
            "service": "Hormone Therapy",
            "delivery_mode": "both",
            "age_group": "adult",
            "note": "Hormone therapy consultations and ongoing medication management.",
        },
        {
            "organization": "Lakeside Gender Health Program",
            "service": "Surgery Referral Support",
            "delivery_mode": "in_person",
            "age_group": "all",
            "note": "Supports referrals for gender-affirming surgery consultation and documentation.",
        },
        {
            "organization": "Lakeside Gender Health Program",
            "service": "Psychiatry",
            "delivery_mode": "both",
            "age_group": "all",
            "note": "Psychiatry referrals available through the hospital network.",
        },
        {
            "organization": "OpenPath Telehealth Care",
            "service": "Hormone Therapy",
            "delivery_mode": "telehealth",
            "age_group": "adult",
            "note": "Virtual hormone therapy consultations available in selected states.",
        },
        {
            "organization": "OpenPath Telehealth Care",
            "service": "Lab Monitoring",
            "delivery_mode": "telehealth",
            "age_group": "adult",
            "note": "Remote lab coordination through partner lab locations.",
        },
        {
            "organization": "Evergreen Affirming Therapy",
            "service": "Mental Health Counseling",
            "delivery_mode": "both",
            "age_group": "all",
            "note": "Affirming therapy for gender exploration, anxiety, depression, and transition-related support.",
        },
        {
            "organization": "Evergreen Affirming Therapy",
            "service": "Surgery Referral Support",
            "delivery_mode": "telehealth",
            "age_group": "adult",
            "note": "Support letters and documentation guidance where clinically appropriate.",
        },
        {
            "organization": "BridgePoint LGBTQ Resource Clinic",
            "service": "Care Navigation",
            "delivery_mode": "in_person",
            "age_group": "all",
            "note": "Helps users find affirming care, community support, and social services.",
        },
        {
            "organization": "BridgePoint LGBTQ Resource Clinic",
            "service": "PrEP and HIV Prevention",
            "delivery_mode": "in_person",
            "age_group": "adult",
            "note": "HIV prevention counseling, testing, and referral support.",
        },
        {
            "organization": "North Star Community Health",
            "service": "Insurance Navigation",
            "delivery_mode": "both",
            "age_group": "adult",
            "note": "Helps patients understand insurance requirements and possible coverage questions.",
        },
        {
            "organization": "North Star Community Health",
            "service": "HRT Follow-Up Care",
            "delivery_mode": "both",
            "age_group": "adult",
            "note": "Follow-up visits for ongoing hormone therapy care and monitoring.",
        },
        {
            "organization": "Cedar Valley Trans Health Program",
            "service": "Voice Therapy",
            "delivery_mode": "in_person",
            "age_group": "adult",
            "note": "Voice therapy referrals through affiliated speech-language pathology services.",
        },
        {
            "organization": "Cedar Valley Trans Health Program",
            "service": "Fertility Preservation",
            "delivery_mode": "in_person",
            "age_group": "adult",
            "note": "Fertility preservation counseling and referral support before or during transition-related care.",
        },
        {
            "organization": "Spectrum Family Medicine",
            "service": "Primary Care",
            "delivery_mode": "in_person",
            "age_group": "adult",
            "note": "Family medicine visits with affirming intake practices.",
        },
        {
            "organization": "Spectrum Family Medicine",
            "service": "Sexual and Reproductive Health",
            "delivery_mode": "both",
            "age_group": "adult",
            "note": "Preventive care, screenings, contraception counseling, and sexual health services.",
        },
        {
            "organization": "Rainbow Bridge Wellness Clinic",
            "service": "PrEP and HIV Prevention",
            "delivery_mode": "both",
            "age_group": "adult",
            "note": "PrEP counseling, HIV/STI testing, and prevention support.",
        },
        {
            "organization": "TrueNorth Virtual Gender Care",
            "service": "Pharmacy Coordination",
            "delivery_mode": "telehealth",
            "age_group": "adult",
            "note": "Helps coordinate prescriptions with the user's preferred pharmacy.",
        },
        {
            "organization": "Community Pride Health Access",
            "service": "Care Navigation",
            "delivery_mode": "both",
            "age_group": "all",
            "note": "Navigation support for finding clinics, benefits, and community resources.",
        },
        {
            "organization": "UnityCare Gender Wellness",
            "service": "Youth Gender Care",
            "delivery_mode": "in_person",
            "age_group": "youth",
            "note": "Youth-focused gender care information and referrals with appropriate consent and guardian requirements.",
        },
    ],
    "AffirmingFeature": [
        {
            "label": "Chosen Name Supported",
            "description": "The provider or clinic supports use of a patient's chosen name in communication, scheduling, and care interactions where possible.",
        },
        {
            "label": "Pronouns Collected and Used",
            "description": "The clinic collects and uses patient pronouns as part of intake or patient communication.",
        },
        {
            "label": "Two-Step Gender Intake",
            "description": "The intake process separately captures current gender identity and sex assigned at birth when medically relevant.",
        },
        {
            "label": "Published Non-Discrimination Policy",
            "description": "The organization has a public non-discrimination policy that includes sexual orientation, gender identity, or gender expression.",
        },
        {
            "label": "Staff LGBTQ Patient-Centered Training",
            "description": "Staff receive training related to LGBTQ+ patient-centered care, respectful communication, and inclusive practice.",
        },
        {
            "label": "Trans-Specific Care Training",
            "description": "Clinical staff have training or experience specifically related to transgender, nonbinary, or gender-diverse care.",
        },
        {
            "label": "Informed Consent HRT Model",
            "description": "The provider uses or supports an informed-consent approach for hormone therapy where clinically and legally appropriate.",
        },
        {
            "label": "Letters and Documentation Support",
            "description": "The provider can support documentation, letters, or referrals for transition-related care when appropriate.",
        },
        {
            "label": "Care Navigation Support",
            "description": "The organization helps patients understand next steps, referrals, insurance questions, or local healthcare resources.",
        },
        {
            "label": "Telehealth Available",
            "description": "The provider offers some form of virtual visit, video visit, or telehealth service.",
        },
        {
            "label": "Lab Coordination Available",
            "description": "The provider helps coordinate required lab testing for hormone therapy, medication monitoring, or preventive care.",
        },
        {
            "label": "Pharmacy Coordination Available",
            "description": "The provider helps patients coordinate prescriptions with pharmacies or medication access workflows.",
        },
        {
            "label": "Gender-Neutral Restrooms",
            "description": "The location provides gender-neutral or all-gender restroom access where available.",
        },
        {
            "label": "Wheelchair Accessible Location",
            "description": "The clinic location is marked as wheelchair accessible or provides accessible entry information.",
        },
        {
            "label": "Multilingual Support",
            "description": "The clinic offers multilingual staff, interpretation, or translated patient support resources.",
        },
    ],
    "ProviderFeature": [
        {
            "provider": "Harbor Inclusive Health Center",
            "feature": "Chosen Name Supported",
            "value": "yes",
            "evidence_note": "Demo evidence: intake materials state that chosen name can be used for scheduling and patient communication.",
            "source_url": "https://example.org/harbor-inclusive-health/patient-info",
            "verified_at": "2026-03-12T10:00:00Z",
        },
        {
            "provider": "Harbor Inclusive Health Center",
            "feature": "Pronouns Collected and Used",
            "value": "yes",
            "evidence_note": "Demo evidence: new patient form includes pronouns field.",
            "source_url": "https://example.org/harbor-inclusive-health/forms",
            "verified_at": "2026-03-12T10:00:00Z",
        },
        {
            "provider": "Lakeside Gender Health Program",
            "feature": "Trans-Specific Care Training",
            "value": "yes",
            "evidence_note": "Demo evidence: program description references a specialized gender health team.",
            "source_url": "https://example.org/lakeside-gender-health/team",
            "verified_at": "2026-03-10T09:30:00Z",
        },
        {
            "provider": "Lakeside Gender Health Program",
            "feature": "Letters and Documentation Support",
            "value": "yes",
            "evidence_note": "Demo evidence: referral page mentions documentation support for surgery consultation.",
            "source_url": "https://example.org/lakeside-gender-health/referrals",
            "verified_at": "2026-03-10T09:30:00Z",
        },
        {
            "provider": "OpenPath Telehealth Care",
            "feature": "Telehealth Available",
            "value": "yes",
            "evidence_note": "Demo evidence: provider is virtual-first and offers telehealth consultations.",
            "source_url": "https://example.org/openpath-telehealth/start",
            "verified_at": "2026-03-14T11:00:00Z",
        },
        {
            "provider": "OpenPath Telehealth Care",
            "feature": "Lab Coordination Available",
            "value": "yes",
            "evidence_note": "Demo evidence: service page describes lab coordination through partner labs.",
            "source_url": "https://example.org/openpath-telehealth/labs",
            "verified_at": "2026-03-14T11:00:00Z",
        },
        {
            "provider": "Evergreen Affirming Therapy",
            "feature": "Letters and Documentation Support",
            "value": "yes",
            "evidence_note": "Demo evidence: therapy intake page mentions documentation support when clinically appropriate.",
            "source_url": "https://example.org/evergreen-therapy/services",
            "verified_at": "2026-03-05T15:20:00Z",
        },
        {
            "provider": "Evergreen Affirming Therapy",
            "feature": "Published Non-Discrimination Policy",
            "value": "yes",
            "evidence_note": "Demo evidence: website footer includes inclusive care and non-discrimination statement.",
            "source_url": "https://example.org/evergreen-therapy/policies",
            "verified_at": "2026-03-05T15:20:00Z",
        },
        {
            "provider": "BridgePoint LGBTQ Resource Clinic",
            "feature": "Care Navigation Support",
            "value": "yes",
            "evidence_note": "Demo evidence: clinic description includes navigation and referral support.",
            "source_url": "https://example.org/bridgepoint-lgbtq/services",
            "verified_at": "2026-03-08T13:45:00Z",
        },
        {
            "provider": "BridgePoint LGBTQ Resource Clinic",
            "feature": "Multilingual Support",
            "value": "yes",
            "evidence_note": "Demo evidence: resource page lists English and Spanish navigation support.",
            "source_url": "https://example.org/bridgepoint-lgbtq/accessibility",
            "verified_at": "2026-03-08T13:45:00Z",
        },
        {
            "provider": "North Star Community Health",
            "feature": "Informed Consent HRT Model",
            "value": "yes",
            "evidence_note": "Demo evidence: hormone care page references informed-consent-based adult hormone therapy workflow.",
            "source_url": "https://example.org/north-star-community/hormone-care",
            "verified_at": "2026-02-28T12:00:00Z",
        },
        {
            "provider": "North Star Community Health",
            "feature": "Pharmacy Coordination Available",
            "value": "yes",
            "evidence_note": "Demo evidence: care team helps coordinate prescription refills and pharmacy questions.",
            "source_url": "https://example.org/north-star-community/patient-support",
            "verified_at": "2026-02-28T12:00:00Z",
        },
        {
            "provider": "Cedar Valley Trans Health Program",
            "feature": "Trans-Specific Care Training",
            "value": "yes",
            "evidence_note": "Demo evidence: multidisciplinary gender health program lists trained specialists.",
            "source_url": "https://example.org/cedar-valley-trans-health/team",
            "verified_at": "2026-03-11T16:10:00Z",
        },
        {
            "provider": "Cedar Valley Trans Health Program",
            "feature": "Gender-Neutral Restrooms",
            "value": "yes",
            "evidence_note": "Demo evidence: location page lists all-gender restroom availability.",
            "source_url": "https://example.org/cedar-valley-trans-health/location",
            "verified_at": "2026-03-11T16:10:00Z",
        },
        {
            "provider": "Spectrum Family Medicine",
            "feature": "Two-Step Gender Intake",
            "value": "yes",
            "evidence_note": "Demo evidence: intake form separates gender identity from sex assigned at birth.",
            "source_url": "https://example.org/spectrum-family-medicine/forms",
            "verified_at": "2026-03-09T10:40:00Z",
        },
        {
            "provider": "Spectrum Family Medicine",
            "feature": "Staff LGBTQ Patient-Centered Training",
            "value": "unknown",
            "evidence_note": "Demo evidence: no public staff training information listed.",
            "source_url": "",
            "verified_at": "2026-03-09T10:40:00Z",
        },
        {
            "provider": "Rainbow Bridge Wellness Clinic",
            "feature": "Lab Coordination Available",
            "value": "yes",
            "evidence_note": "Demo evidence: clinic offers HIV/STI testing and lab-related preventive care.",
            "source_url": "https://example.org/rainbow-bridge-wellness/services",
            "verified_at": "2026-03-13T14:15:00Z",
        },
        {
            "provider": "TrueNorth Virtual Gender Care",
            "feature": "Telehealth Available",
            "value": "yes",
            "evidence_note": "Demo evidence: provider is virtual-only and supports video visits.",
            "source_url": "https://example.org/truenorth-virtual-care/get-started",
            "verified_at": "2026-03-15T09:00:00Z",
        },
        {
            "provider": "Community Pride Health Access",
            "feature": "Care Navigation Support",
            "value": "yes",
            "evidence_note": "Demo evidence: nonprofit description includes insurance and provider navigation support.",
            "source_url": "https://example.org/community-pride-access/navigation",
            "verified_at": "2026-03-06T17:30:00Z",
        },
        {
            "provider": "UnityCare Gender Wellness",
            "feature": "Wheelchair Accessible Location",
            "value": "yes",
            "evidence_note": "Demo evidence: location profile marks accessible entry and elevator access.",
            "source_url": "https://example.org/unitycare-gender-wellness/location",
            "verified_at": "2026-03-07T11:25:00Z",
        },
    ],
}
