# Generated by Django 6.0.3 on 2026-04-02 07:00

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderOrganization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('org_type', models.CharField(choices=[('clinic', 'Clinic'), ('hospital_program', 'Hospital Program'), ('telehealth', 'Telehealth'), ('private_practice', 'Private Practice'), ('nonprofit', 'Nonprofit')], max_length=50)),
                ('description', models.TextField()),
                ('website_url', models.URLField(blank=True, null=True)),
                ('booking_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('gender_neutral_restrooms', models.BooleanField(default=False)),
                ('public_transit_notes', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='provider_organizations.providerorganization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_mode', models.CharField(choices=[('in_person', 'In Person'), ('telehealth', 'Telehealth'), ('both', 'Both')], max_length=20)),
                ('age_group', models.CharField(choices=[('adult', 'Adult'), ('youth', 'Youth'), ('all', 'All Ages')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='provider_organizations.providerorganization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='provider_organizations.service')),
            ],
        ),
    ]
