# Generated by Django 6.0.3 on 2026-04-15 12:06

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider_organizations", "0002_alter_organizationservice_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffirmingFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="label", unique=True
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProviderFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("evidence_note", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="provider_organizations.affirmingfeature",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affirming_features",
                        to="provider_organizations.providerorganization",
                    ),
                ),
            ],
        ),
    ]
