# Generated by Django 6.0.3 on 2026-06-09 11:39

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def reject_duplicate_pending_claims(apps, schema_editor):
    Claim = apps.get_model(
        "provider_organizations",
        "ProviderOrganizationClaim",
    )
    pending_claims = (
        Claim.objects.filter(status="pending", claimant_id__isnull=False)
        .order_by("claimant_id", "created_at", "pk")
    )
    first_claim_by_user = {}
    reviewed_at = timezone.now()

    for claim in pending_claims.iterator():
        if claim.claimant_id not in first_claim_by_user:
            first_claim_by_user[claim.claimant_id] = claim.pk
            continue

        claim.status = "rejected"
        claim.reviewed_at = reviewed_at
        claim.admin_note = (
            "Automatically rejected because an earlier claim from this account "
            "is still pending."
        )
        claim.save(
            update_fields=("status", "reviewed_at", "admin_note"),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("provider_organizations", "0005_providerorganizationclaim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            reject_duplicate_pending_claims,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="providerorganizationclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("claimant",),
                name="unique_pending_claim_per_user",
            ),
        ),
    ]
