# Generated by Django 6.0.3 on 2026-07-17 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('current_filters', models.JSONField(blank=True, default=dict)),
                ('current_sort', models.CharField(default='name', max_length=32)),
                ('result_provider_slugs', models.JSONField(blank=True, default=list)),
                ('selected_provider_slug', models.SlugField(blank=True, max_length=255)),
                ('pending_clarification', models.CharField(blank=True, max_length=300)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('assistant_message', models.TextField()),
                ('intent', models.CharField(choices=[('search_providers', 'Search providers'), ('provider_details', 'Provider details'), ('clarification', 'Clarification')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='provider_chat.chatconversation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', 'expires_at'], name='chat_user_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('session_key', '')), models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), _connector='OR'), name='chat_conversation_has_one_owner'),
        ),
        migrations.AddIndex(
            model_name='chatturn',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_turn_created_idx'),
        ),
    ]
